is: [pageable: { default_per: 50, max_per: 1000 }]
queryParameters:
  geographic_area_id:
    description: |
      Identifier for the geographic area.
    type: integer
    required: false
    example: 33609
  otu_id:
    description: |
      Identifier for the otu for which distribution is asserted.
    type: integer
    required: false
  otu_id[]:
    description: |
      Array of identifier IDs for otus for which distribution is asserted.
    type: integer array
    required: false
  recent:
    description: |
      Include recent searchs?.
    type: string boolean
    required: false
    example: "false"

responses:
  200:
    body:
      application/json:
        type: AssertedDistribution[]
        maxItems: 100
        uniqueItems: true
        example: !include /examples/asserted_distributions-result-example.json
