is: [pageable: { default_per: 100, max_per: 1000 }]
queryParameters:
  biological_relationship_id:
    description: |
      Identifier for the relationship.
    type: integer
    required: false
    example:  1
#  biological_association_subject_id:
#    description: |
#      Identifier for the subject.
#    type: integer
#    required: false
#    example: 23068
#  biological_association_object_id:
#    description: |
#      Identifier for the object.
#    type: integer
#    required: false
#    example: 130025
  biological_association_subject_type:
    description: |
      Subject part of the association triple
    type: string
    required: false
    example: "Otu"
  biological_association_object_type:
    description: |
      Object part of the association triple
    type: string
    required: false
    example: "Otu"
  subject_global_id:
    description: |
      Identifier for the subject.
    type: string
    required: false
    example: "gid://taxon-works/Otu/23068"
  object_global_id:
    description: |
      Identifier for the object.
    type: string
    required: false
    example: "gid://taxon-works/Otu/130025"
  any_global_id:
    description: |
      Any global identifier for the relationship.
    type: string
    required: false
#  origin_citation_attributes:
#    description: |
#      [:id, :_destroy, :source_id, :pages]
#    type: string
#    required: false
#  citations_attributes:
#    description: |
#      [:id, :is_original, :_destroy, :source_id, :pages, :citation_object_id,, :citation_object_type]
#    type: string
#    required: false

responses:
  200:
    body:
      application/json:
        type: BiologicalAssociation[]
        maxItems: 100
        uniqueItems: true
        example: !include /examples/biological_associations-result-example.json
