#%RAML 1.0 Trait

queryParameters:
  citations:
    description:  |
      true: with Citations
      false: without Citations
      nil: ignored
    type: boolean
    required: false
  citation_documents:
    description:  |
      true: has Citations, sources have documents
      false: has Citations, sources don't have documents
      nil: ignored
    type: boolean
    required: false
  origin_citation:
    description:  |
      true: with Origin Citation
      false: without Origin Citations
      nil: ignored
    type: boolean
    required: false
