#%RAML 1.0 Trait

queryParameters:
  citations:
    description:  |
      Citations ??
    type: integer
    required: false
  origin_citation:
    description:  |
      Origin citatation ??
    type: integer
    required: false
