is: [pageable: { default_per: 100, max_per: 1000 }]
queryParameters:
  collecting_events_wildcards[]:
    description: |
      ATTRIBUTES that can be wildcarded.
      See https://www.rubydoc.info/github/SpeciesFileGroup/taxonworks/CollectingEvent,
      Instance Attribute Summary, which details columns of the collecting_events table.
    type: string array
    required: false
#    example:  "?"
  collector_id:
    description:  |
      A single collector ID
    type: string integer
    required: false
  collector_id[]:
    description:  |
      List of collector IDs
    type: string integer array
    required: false
  collector_ids_or:
    description:  |
      Find collecting events with ANY one of these collectors (true) or ALL of these collectors (false)
    type: string boolean
    required: false
  geo_json:
    description:
      geoJSON of the search area
    type: string
    required: false
  geographic_area_id:
    description: |
      Single geographic area ID for search
    type: integer
    required: false
  geographic_area_id[]:
    description: |
      List of geographic area IDs for search
    type: integer
    required: false
#    example: 2593
  in_labels:
    description: |
      Wildcard wrapped match against any label
    type: string
    required: false
#    example: "?"
  in_verbatim_locality:
    description: |
      Wildcard wrapped match against verbatim locality (via ATTRIBUTES)
    type: string
    required: false
#    example: "?"
  keyword_id_and[]:
    description: |
      List of keyword IDs for associated collecting events where all enumerated keywords are present.
    type: string integer array
    required: false
  keyword_id_or[]:
    description: |
      List of keyword IDs for associated collecting events where any of the enumerated keywords are present.
    type: string integer array
    required: false
  otu_ids:
    description: |
      A single OTU ID to match.
    type: string integer
    required: false
  otu_id[]:
    description: |
      List of OTU IDs to all match.
    type: string integer array
    required: false
#    example: 3809
  md5_verbatim_labels: |
      Include metadata for verbatim labels.
    type: string boolean
    required: false
#    example: "false"
  radius:
    description: |
      Search area radius in meters.
    type: integer
    required: false
  recent:
    description: |
      Include metadata for recent searches
    type: string boolean
    required: false
    example: "false"
#  spatial_geographic_area_id:
#    description: |
#      Reference a geographic_area in a spatial query
#    type: string integer
#    required: false
#  spatial_geographic_area_id[]:
#    description: |
#      Reference a list of geographic areas in a spatial query
#    type: string integer
#    required: false
  spatial_geographic_areas:
    description: |
      Find CollectingEvents having spatial geographic areas
    type: string boolean
    required: false
#    example: "false"
  wkt:
    description: |
      Well Known Text describing the search area
    type: string
    required: false

responses:
  200:
    body:
      application/json:
        type: CollectingEvent[]
        maxItems: 100
        uniqueItems: true
        example: !include /examples/collecting_events-result-example.json
