#%RAML 1.0 Trait

queryParameters:
  data_attribute_exact_value:
    description:  |
      blah blah
    type: integer
    required: false
  data_attribute_predicate_id:
    description:  |
      blah blah
    type: integer
    required: false
  data_attribute_value:
    description:  |
      blah blah
    type: integer
    required: false
  data_attributes:
    description:  |
      blah blah
    type: integer
    required: false
