is: [pageable: { default_per: 50, max_per: 1000 }]
queryParameters:
  project_id:
    description: |
      The project for the data attribute search
    type: integer
    required: true
    example: 2

responses:
  200:
    body:
      application/json:
        type: DataAttribute[]
        maxItems: 100
        uniqueItems: true
        example: !include /examples/data_attributes-result-example.json
