is: [pageable: { default_per: 50, max_per: 1000 }]
responses:
  200:
    body:
      application/json:
        type: DataAttribute[]
        maxItems: 100
        uniqueItems: true
        example: !include /examples/data_attributes_id-result-example.json
