is: [pageable: { default_per: 100, max_per: 1000 }]
queryParameters:
responses:
  200:
    body:
      application/json:
        type: DataAttribute[]
        maxItems: 100
        uniqueItems: true
        example: !include /examples/data_attributes-result-example.json
