#%RAML 1.0 Trait

queryParameters:
  image_id:
    description: |
      ID for the image object to be found.
    type: integer
    required: false
  image_id[]:
    description: |
      Array of IDs for the image objects to be found.
    type: integer
    required: false
  images:
    description: |
      true: has images
      false: doesn't have images
    type: boolean
    required: false
