is: [pageable: { default_per: 50, max_per: 1000 }]
queryParameters:
  identifier:
    description: |
      Search for
    type: string
    required: false
  identifier_object_id:
    description: |
      Metadata for an ID of an object.
    type: integer
    required: false
  identifier_object_id[]:
    description: |
      Metadata for an array of IDs of objects
      identifier_object_id[]=47&identifier_object_id[]=2232.
    type: integer
    required: false
  identifier_object_type:
    description: |
      Metadata for an object type, case sensitive.
    type: string
    required: false
  identifier_object_type[]:
    description: |
      Metadata for an array of object types.
      ?identifier_object_type[]=CollectionObject&identifier_object_type[]=Serial
    type: string
    required: false
  namespace_id:
    description: |
      The ID for the namespace name.
    type: integer
    required: false
  namespace_name:
    description: |
      The namespace name for the identifier.
    type: string
    required: false
  namespace_short_name:
    description: |
      The short version of the namespace name for the identifier.
    type: string
    required: false
  object_global_id:
    description: |
      Filter by object global ID
    type: integer
    required: false
  type:
    description: |
      Include metadata for a specific type, e.g, "Identifier::Local::CatalogNumber"
    type: string
    required: false

responses:
  200:
    body:
      application/json:
        type: Identifier[]
        maxItems: 100
        uniqueItems: true
        example: !include /examples/identifiers-result-example.json
