#%RAML 1.0 Trait

queryParameters:
  identifier:
    description:  |
      ??
    type: ??
    required: false
  identifier_end:
    description:  |
      ??
    type: ??
    required: false
  identifier_exact:
    description:  |
      ??
    type: ??
    required: false
  identifier_start:
    description:  |
      ??
    type: ??
    required: false
  identifier_type:
    description:  |
      Include metadata for a specific type, e.g, "Identifier::Local::CatalogNumber"
    type: string
    required: false
  identifier_type[]:
    description:  |
      ??
    type: ??
    required: false
  identifiers:
    description:  |
      ??
    type: ??
    required: false
  local_identifiers:
    description:  |
      ??
    type: ??
    required: false
  match_identifiers:
    description:  |
      ??
    type: ??
    required: false
  match_identifiers_delimiter:
    description:  |
      ??
    type: ??
    required: false
  match_identifiers_type:
    description:  |
      ??
    type: ??
    required: false
  namespace_id:
    description:  |
      The ID for the namespace name.
    type: integer
    required: false

