is: [pageable: { default_per: 100, max_per: 1000 }]
queryParameters:
  ancestor_id_target:
  biocuration_class_id:
  biocuration_class_id[]:
  collection_object_id:
  collection_object_id[]:
  depiction:
  identifier:
  identifier_end:
  identifier_exact:
  identifier_start:
  image_id[]:
  keyword_ids[]:
  otu_id:
  otu_id[]:
  image_id:
  sled_image_id:
  sled_image_id[]:
  taxon_name_id:
  taxon_name_id[]:
  user_id: # user
  user_target:
  user_date_start:
  user_date_end:
