#%RAML 1.0 Trait

queryParameters:
  note_object_id:
    description: |
      Single identifier for the note object.
    type: integer
    required: false
  note_object_id[]:
    description: |
      Array of identifiers for the note objects#, e.g., note_object_id[]=3254&note_object_id[]=197.
    type: integer
    required: false
  note_object_type:
    description: |
      Object type for the note, such as TaxonDetermination, TaxonName, Otu, etc.
    type: string
    required: false
  note_object_type[]:
    description: |
      Array of object types for the notes#, note_object_type[]=TaxonDetermination&note_object_type[]=Otu.
    type: string
    required: false
  object_global_id:
    description: |
      Identifier for the note's source.
    type: integer
    required: false
  text:
    description: |
      Text segment to be searched for in notes.
    type: string
    required: false
