#%RAML 1.0 Trait

queryParameters:
  note_exact:
    description: |
      return Note if the exact text matches the note object.
    type: boolean
    required: false
  note_text:
    description: |
      Search for the exact text matching notes.
    type: string
    required: false
  notes:
    description: |
      True: only return objects with notes.
    type: boolean
    required: false
