#%RAML 1.0 Trait

queryParameters:
  note_exact:
    description: |
      Search for the exact text matching the note object to be found.
    type: integer
    required: false
  note_text:
    description: |
      Array of IDs for the notes to be found.
    type: integer
    required: false
  notes:
    description: |
      Find all notes that reference any objects that have a note_object_id.
      This param should only be used in tandem with note_object_type.
    type: integer
    required: false
