is: [pageable: { default_per: 50, max_per: 1000 }]
queryParameters:
  observation_matrix_id:
    description: |
      Single ID for observation matrix.
    type: integer
    required: false
  observation_matrix_id[]:
    description: |
      Array of IDs for observation matrices.
    type: integer array
    required: false

responses:
  200:
    body:
      application/json:
        type: ObservationMatrix[]
        maxItems: 100
        uniqueItems: true
        example: !include /examples/observation_matrices-result-example.json
