is: [pageable: { default_per: 100, max_per: 1000 }]
queryParameters:
  asserted_distribution_ids[]:
    description: |
      List of asserted distribution IDs.
    type: string integer array
    required: false
  data_attributes_attributes:
    description: |
      [ :id, :_destroy, :controlled_vocabulary_term_id, :type, :attribute subject_id:, attribute_subject_type, :value ]
    type: mixed parameter array
    required: false
  name:
    description: |
      Name (label) of the OTU.
    type: string
    required: false
  otu_id:
    description: |
      ID for a single OTU.
    type: integer
    required: false
  otu_ids[]:
    description: |
      List of OTU IDs.
    type: string integer array
    required: false
  taxon_name_classification_ids[]:
    description: |
      List of classification IDs.
    type: string integer array
    required: false
  taxon_name_id:
    description: |
      ID for a given taxon
    type: integer
    required: false
  taxon_name_ids[]:
    description: |
      List of taxon name IDs.
    type: string integer array
    required: false
  taxon_name_relationships_ids[]:
    description: |
      List of relationship IDs
    type: string integer array
    required: false

responses:
  200:
    body:
      application/json:
        type: Otu[]
        maxItems: 100
        uniqueItems: true
        example: !include /examples/otus-result-example.json
