queryParameters:
  page:
    displayName: Page Number
    description: The page of <<resourcePathName>> result set to retrieve.
    type: integer
    required: false
    example: 5
    default: 0
  per:
    displayName: Results per Page
    description: The number of <<resourcePathName>> per page.
    type: integer
    required: false
    example: 10
    default: <<default_per>>
    minimum: 1
    maximum: <<max_per>>
responses:
  200:
    headers:
      Pagination-Total:
        description: Total number of <<resourcePathName>> in result set.
        type: integer
        example: 30034
      Pagination-Total-Pages:
        description: Total number of pages for result set.
        type: integer
        example: 300
      Pagination-Page:
        description: Page number of result set.
        type: integer
        example: 5
      Pagination-Per-Page:
        description: Number of <<resourcePathName>> per Page.
        type: integer
        example: 100
      Pagination-Previous-Page:
        description: Previous page number.
        type: integer
        example: 4
      Pagination-Next-Page:
        description: Next page number.
        type: integer
        example: 6
