is: [pageable: { default_per: 100, max_per: 1000 }]
queryParameters:
  source_id:
    description: |
      Source identifier for a single source.
    type: integer
    required: false
  first_name:
    description: |
      Filter by person first name or fragment. Matching is case insensitive. Use " " for "and". See also `exact`.
    type: string
    required: false
    example: "Megan"
  last_name:
    description: |
      Filter by person last name or fragment. Matching is case insensitive. Use " " for "and". See also `exact`.
    type: string
    required: false
    example: "Murphey"
  last_name_starts_with:
    description: |
      Filter by person last name fragment (from beginning). Matching is case insensitive. Use " " for "and". See also `exact`.
    type: string
    required: false
    example: "Murp"
  limit_to_roles:
    description: |
      Filter by person role(s), e.g., SourceAuthor, SourceEditor, SourceSource, TaxonNameAuthor. Matching is case insensitive. Use " " for "and". See also `exact`.
    type: string
    required: false
    example: "SourceAuthor"
  project_id:
    description: |
      The project for the source search
    type: integer
    required: true

responses:
  200:
    body:
      application/json:
        type: Person[]
        maxItems: 100
        uniqueItems: true
        example: !include /examples/people-result-example.json
