is: [pageable: { default_per: 100, max_per: 1000 }]
queryParameters:
  source_id:
    description: |
      Source identifier for a single source.
    type: integer
    required: false
  last_name_starts_with:
    description: |
      Filter by person . Matching is case insensitive. Use " " for "and". See also `exact`.
    type: string
    required: false
    example: "Murp"
  project_id:
    description: |
      The project for the source search
    type: integer
    required: true

responses:
  200:
    body:
      application/json:
        type: Source[]
        maxItems: 100
        uniqueItems: true
        example: !include /examples/people-result-example.json
