#%RAML 1.0 Trait

usage: Request a valid project token.
queryParameters:
  project_token:
    displayName: Project Token
    description: A project (not User) token indicating the target project.
    type: string
    example:  rIO2oWS603c5W5laQ8ornn