#%RAML 1.0 Trait

queryParameters:
  keyword_id_and:
    description:  |
      Keyword ID for tags for this model instances where this keyword is present.
    type: integer
    required: false
  keyword_id_and[]:
    description:  |
      List of keyword IDs for tags for this model instances where all enumerated keywords are present.
    type: integer
    required: false
  keyword_id_or:
    description:  |
      Keyword ID for tags for this model instances where this keyword is present.
    type: integer
    required: false
  keyword_id_or[]:
    description:  |
      List of keyword IDs for tags for this model instances where any of the enumerated keywords are present.
    type: integer
    required: false
  tags:
    description:  |
      true: return objects that have tags.
    type: boolean
    required: false
