#%RAML 1.0 Trait

queryParameters:
  keyword_id_and:
    description:  |
      blah blah
    type: integer
    required: false
  keyword_id_and[]:
    description:  |
      blah blah
    type: integer
    required: false
  keyword_id_or:
    description:  |
      blah blah
    type: integer
    required: false
  keyword_id_or[]:
    description:  |
      blah blah
    type: integer
    required: false
  tags:
    description:  |
      blah blah
    type: string
    required: false
