is: [pageable: { default_per: 50, max_per: 1000 }]
queryParameters:
  author:
    description: |
      Filter by authors (inside `cached_author_year` property). Matching is case insensitive. Use "&" for "and". See also `exact`.
    type: string
    required: false
    example: "Smith & Johnson, 2019"
  authors:
    description: |
      When `true` then only return taxon names that have an author string present.
    type: boolean
    required: false
    example: [true, false, TRUE, FALSE, True, False]
  citations:
    description: |
      When `true` then only return taxon names that have citations attached to them.
    type: boolean
    required: false
    enum:  [true, false, TRUE, FALSE, True, False]
    example: false
  descendants:
    description: |
      Filter by parenthood. When set to true and one or more taxon_name_id values are provided then the request matches taxa which are children of at least one of the taxa specified by the taxon_name_ids. Has no effect if taxon_name_id is not provided.
    type: boolean
    required: false
    default: false
    example: true
  exact:
    description: |
      True if filter matching must be exact, false if partial matches are allowed.
    type: boolean
    required: false
    default: false
    example: true
  leaves:
    description: |
      If 'true' filters by names having no descendents or with descendants if 'false'.
    type: boolean | nil
    required: false
    default: nil
    example: true
  name:
    description: |
      Filter to apply on full taxon name (`cached` property). Matching is case insensitive. See also `exact`.
    type: string
    required: false
    example: "Aus"
  nomenclature_code[]:
    description: |
      Filter by nomenclature code.
    type: string
    enum: [ICZN, ICBN, ICN, ICTV]
    required: false
    example: ICZN
  nomenclature_group[]:
    description: |
      Filter by nomenclature group.
    type: string
    enum: [Higher, Family, Genus, Species]
    required: false
    example: Genus
  otus:
    description: |
      When `true` then only return taxon names that are linked to one or more Otus.
    type: boolean
    enum: [true, false, TRUE, FALSE, True, False]
    required: false
    example: true
  project_id:
    description: |
      Project identifier. In the absence of a project token you must provide this parameter.
    type: integer
    required: false
    example: 1
  taxon_name_id[]:
    description: |
      Return only taxon names with these ids. To also return children see `descendants`.
    type: integer[]
    required: false
    example: [1, 5]
  taxon_name_relationship_type[]:
    description: |
      Filter by names having relationships of these types
    type: array
    required: false
    example: TaxonNameRelationship::Iczn::Invalidating
  taxon_name_type[]:
    description: |
      Return only taxon names of the provided class. Case sensitive. Only `Protonym`, `Combination`, and `Hybrid` are supported.
    type: string
    required: false
    example: Protonym
  type_metadata:
    description: |
      Boolean. When `true` then only return taxon names that are linked to a type specimen (collection object).
    type: string
    required: false
    enum: [true, false, TRUE, FALSE, True, False]
    example: TRUE
  updated_since:
    description: |
      Names updated (modified_at property) since this datetime.
    type: datetime
    required: false
    example: 2019-05-20T13:30:00
  validity:
    description: |
      Filter by validity. True if only valid, false if only invalid, nil if both
    type: string | nil
    required: false
    default: nil
    example: true
  year:
    description: |
      Filter by authority year (inside `cached_author_year` property). Format is 'YYYY'.
    type: string
    pattern: "[0-9]{4}"
    required: false
    example: "2019"
responses:
  200:
    body:
      application/json:
        type: TaxonName[]
        maxItems: 100
        uniqueItems: true
        example: !include /examples/taxon_names-result-example.json
