is: [pageable: { default_per: 100, max_per: 1000 }]
queryParameters:
  subject_taxon_name_id:
    description: |
      A single ID for the subject taxon name.
    type: string integer
    required: false
    example:  377
  subject_taxon_name_id[]:
    description: |
      Array of IDs for the subject taxon names.
    type: string integer array
    required: false
  object_taxon_name_id:
    description: |
      A single ID for the object taxon name.
    type: string integer
    required: false
  object_taxon_name_id[]:
    description: |
      Array of IDs for the onject taxon names.
    type: string integer array
    required: false
  taxon_name_relationship_type:
    description: |
        One exact NOMEN/Ruby class/type
    type: string
    required: false
  taxon_name_relationship_type[]:
    description: |
        One or more exact NOMEN/Ruby class/type
    type: string array
    required: false

responses:
  200:
    body:
      application/json:
        type: TaxonNameRelationship[]
        maxItems: 100
        uniqueItems: true
        example: !include /examples/taxon_name_relationships-result-example.json
