#%RAML 1.0 Trait

queryParameters:
  user_date_end:
    description:  |
      blah blah
    type: integer
    required: false
  user_date_start:
    description:  |
      blah blah
    type: integer
    required: false
  user_id:
    description:  |
      blah blah
    type: integer
    required: false
  user_target:
    description:  |
      blah blah
    type: integer
    required: false
  updated_since:
    description:  |
      blah blah
    type: date-only
    required: false
