#%RAML 1.0 Trait

usage: Request valid user api token.
queryParameters:
  project_token:
    displayName: Token
    description: A User (not project) token indicating the user. Don't use together with a project token.
    type: string
    example:  hp7-CAdxGHZLtyiq4n8hmw
    required: false
