is: [citations, data_attributes, identifiers, Notes, tags, users, pageable: { default_per: 50, max_per: 1000 }]
queryParameters:
  asserted_distribution_id:
    description: |
      ID for a specific asserted distribution
      type: integer
      required: false
  asserted_distribution_id[]:
    description: |
      IDs for specific asserted distributions
    type: integer array
    required: false
  descendants:
    description: |
      True: include descendants of taxon_name_id in scope, else
      type: boolean
      required: false
  geo_json:
    description: |
      Flag to return result as geoJSON
    type: boolean
    required: false
  geographic_area_id:
    description: |
      Identifier for the geographic area.
    type: integer
    required: false
    example: 33609
  geographic_area_id[]:
    description: |
      Identifiers for specific geographic areas.
    type: integer
    required: false
  geographic_area_mode:
    description:
      Flag to set area mode, in conjunction with geographic_area_id/geographic_area_id[]
        nil - non-spatial match by only those records matching the geographic_area_id exactly
        true - spatial match
        false - non-spatial match (descendants)
    type: boolean, nil
    required: false
  otu_id:
    description: |
      Identifier for the otu for which distribution is asserted.
    type: integer
    required: false
  otu_id[]:
    description: |
      Array of identifier IDs for otus for which distribution is asserted.
    type: integer array
    required: false
  presence:
    description: |
      true: return AssertedDistribution where the OTU is asserted as present according to the Sourcet;
      false: return data where the OTU is asserted as absent according to the Source;
      nil: not applied.
    type: boolean
    required: false
  radius:
    description: |
      Meters around shape boundary, 100m by default
    type: integer
    required: false
  taxon_name_id:
    description: |
      Return results for all OTUs corresponding to this taxon_name_id.
    type: integer
    required: false
  taxon_name_id[]:
    description: |
      Return results for all OTUs corresponding to these IDs.
    type: integer array
    required: false
  wkt:
    description: |
      WKT shape to search for asserted distributions
    type: string
    required: false

responses:
  200:
    body:
      application/json:
        type: AssertedDistribution[]
        maxItems: 100
        uniqueItems: true
        example: !include /examples/asserted_distributions-result-example.json
