is: [citations, identifiers, notes, tags, users, pageable: { default_per: 50, max_per: 1000 }]
queryParameters:
  biological_association_id:
    description: |
      Search for a BiologicalAssociation by ID.
    type: integer
    required: false
  biological_association_id[]:
    description: |
      Search for BiologicalAssociations by IDs.
    type: integer array
    required: false
  biological_associations_graph_id:
    description: |
      Search by BiologicalAssociations graph ID for the associations.
    type: integer
    required: false
  biological_associations_graph_id[]:
    description: |
      Search by IDs of graphs for associations.
    type: integer array
    required: false
  biological_relationship_id:
    description: |
      Search for a BiologicalRelationship by ID.
    type: integer
    required: false
  biological_relationship_id[]:
    description: |
      Search for a BiologicalRelationships by IDs.
    type: integer array
    required: false
  collecting_event_id:
    description: |
      All BiologicalAssociations with CollectionObjects linked to a CollectingEvent.
    type: integer
    required: false
  collecting_event_id[]:
    description: |
      All BiologicalAssociations with CollectionObjects linked to one or more CollectingEvents.
    type: integer array
    required: false
  collection_object_id:
    description: |
      Find BiologicalRelationships with CollectionObject (only) matching subject OR object.
    type: integer
    required: false
  collection_object_id[]:
    description: |
      Search by collection object IDs.
    type: integer array
    required: false
  descendants:
    description: |
      True: include descendant OTUs.
    type: boolean
    required: false
  exclude_taxon_name_relationship:
    description: |
       True: return relationships *excluding* those linked by biological_relationship_id.
    type: boolean
    required: false
  geo_json:
    description: |
      Flag to return result as geoJSON
    type: boolean
    required: false
  geographic_area_id:
    description: |
      Identifier for the geographic area.
    type: integer
    required: false
  geographic_area_id[]:
    description: |
      Identifiers for specific geographic areas.
    type: integer array
    required: false
  geographic_area_mode:
    description:
      Flag to set area mode, in conjunction with geographic_area_id/geographic_area_id[]
        nil - non-spatial match by only those records matching the geographic_area_id exactly
        true - spatial match
        false - non-spatial match (descendants)
    type: boolean, nil
    required: false
  object_biological_property_id:
    description: |
      Find all BiologicalAssociations with object having this property ID.
    type: integer array
    required: false
  object_biological_property_id[]:
    description: |
      Find all BiologicalAssociations with object having these property IDs.
    type: integer array
    required: false
  object_object_global_id:
    description: |
      Find all BiologicalAssociations with object having this global ID.
    type: integer array
    required: false
  object_object_global_id[]:
    description: |
      Find all BiologicalAssociations with object having these global IDs.
    type: integer array
    required: false
  object_taxon_name_id:
    description: |
      Find all BiologicalAssociations matching this (valid !) TaxonName or its children.
    type: integer array
    required: false
  object_taxon_name_id[]:
    description: |
      Find all BiologicalAssociations matching these (valid !) TaxonNames or their children.
    type: integer array
    required: false
  object_type:
    description: |
      Limit search to a specific subject type: Otu, CollectionObject; nil or not present means any.
    type: string
    required: false
  otu_id:
    description: |
      Find BiologicalAssociations with OTU (only) matching subject OR object.
    type: integer array
    required: false
  otu_id[]:
    description: |
      Array of OTU IDs for BiologicalAssociations with OTUs (only) matching subject OR object.
    type: integer array
    required: false
  subject_biological_property_id:
    description: |
      Find all BiologicalAssociations with subject having this property ID.
    type: integer array
    required: false
  subject_biological_property_id[]:
    description: |
      Find all BiologicalAssociations with subject having these property IDs.
    type: integer array
    required: false
  subject_object_global_id:
    description: |
      Find all BiologicalAssociations with subject having this global ID.
    type: integer array
    required: false
  subject_object_global_id[]:
    description: |
      Find all BiologicalAssociations with subject having these global IDs.
    type: integer array
    required: false
  subject_taxon_name_id:
    description: |
      Find all BiologicalAssociations matching this (valid !) TaxonName or its children.
    type: integer
    required: false
  subject_taxon_name_id[]:
    description: |
      Find all BiologicalAssociations matching these (valid !) TaxonNames or their children.
    type: integer array
    required: false
  subject_type:
    description: |
      Limit search to a specific subject type: Otu, CollectionObject; nil or not present means any.
    type: string
    required: false
  taxon_name_id:
    description: |
      Find all BiologicalAssociations matching this name or its children linked to this taxon_name_id.
    type: integer
    required: false
  taxon_name_id[]:
    description: |
      Find all BiologicalAssociations matching these names or their children linked to these taxon_name_id.
    type: integer array
    required: false
  taxon_name_id_mode:
  wkt:
    description: |
      WKT shape to search for biological associations.
    type: string
    required: false

responses:
  200:
    body:
      application/json:
        type: BiologicalAssociation[]
        maxItems: 100
        uniqueItems: true
        example: !include /examples/biological_associations-result-example.json
