is: [polymorphic, pageable: { default_per: 50, max_per: 1000 }]
queryParameters:
  attribute_subject_id:
    description: |
      ??
    type: integer
    required: false
  attribute_subject_type:
    description: |
      ??
    type: string
    required: false
  data_attribute_id:
    description: |
      ??
    type: integer
    required: false
  data_attribute_id[]:
    description: |
      ??
    type: integer array
    required: false
  controlled_vocabulary_term_id:
    description: |
      ??
    type: integer
    required: false
  controlled_vocabulary_term_id[]:
    description: |
      ??
    type: integer array
    required: false
  import_predicate:
    description: |
      ??
    type: string
    required: false
  type:
    description: |
      ??
    type: string
    required: false
 value:
    description: |
      ??
    type: string
    required: false

responses:
  200:
    body:
      application/json:
        type: DataAttribute[]
        maxItems: 100
        uniqueItems: true
        example: !include /examples/data_attributes-result-example.json
