is: [citations, depictions, identifiers, notes, tags, users, pageable]
queryParameters:
  descriptor_id:
    description: |
      Return results for this ID.
    type: integer
    required: false
  descriptor_id[]:
    description: |
      Return results for these IDs.
    type: integer array
    required: false
  descriptor_type:
    description: |
      A fully qualified type, e.g., Descriptor::Continuous.
    type: string
    required: false
  descriptor_type[]:
    description: |
      An array of fully qualified types.
    type: string array
    required: false
  observation_matrices:
    description: |
      Return results for observation matrices.
    type: boolean
    required: false
  observation_matrix_id:
    description: |
      Return results for this observation matrix ID.
    type: integer
    required: false
  observation_matrix_id[]:
    description: |
      Return results for these observation matrix IDs.
    type: integer array
    required: false
  observations:
    description: |
      Return results for observations.
    type: boolean
    required: false
  term:
    description: |
      Match this string against descriptor name, short_name, description, description_name, key_name.
    type: string
    required: false
  term_exact:
    description: |
      Used with term; exact match vs term found in field.
    type: boolean
    required: false
  term_target:
    description: |
      Used with term; designates which field to match against.
    type: string
    required: false

responses:
  200:
    body:
      application/json:
        type: Extract[]
        maxItems: 100
        uniqueItems: true
        example: !include /examples/descriptors-result-example.json

