is: [users, pageable: { default_per: 50, max_per: 1000 } ]
queryParameters:
  dwc_occurrence_id:
    description: |
      ID of Occurrance
    type: integer
    required: false
  dwc_occurrence_id[]:
    description: |
      Array of IDs of Occurrances
    type: integer array
    required: false
  dwc_occurrence_object_id:
    description: |
      ID of Occurrances object
    type: integer
    required: false
  dwc_occurrence_object_id[]:
    description: |
      Array of IDs of Occurrances object IDs
    type: integer array
    required: false
  dwc_occurrence_object_type:
    description: |
      Single ID of Occurrances object types
    type: integer
    required: false
  dwc_occurrence_object_type[]:
    description: |
      Array of IDs of Occurrances object types
    type: integer array
    required: false

responses:
  200:
    body:
      application/json:
        type: DWCOccurrence[]
        maxItems: 100
        uniqueItems: true
        example: !include /examples/dwc_occurrences-result-example.json
