is: [citations, containable, data_ranges, protocols, tags, pageable]
queryParameters:
  collection_object_id:
    description: |
      Return results for this collection object ID.
    type: integer
    required: false
  collection_object_id[]:
    description: |
      Return results for these collection object IDs.
    type: integer
    required: false
  descendants:
    description: |
      Return all extracts linked to OTUs AND CollectionObject that is self or descendant linked
    type: boolean
    required: false
  exact_verbatim_anatomical_origin:
    description: |
      Return result if true: has this exact anatomical origin; false:does not have this origin; nil: disregard.
    type: boolean
    required: false
  extract_end_date_range:
    description: |
      A date in the format yyyy-mm-dd.
    type: datetime
    required: false
  extract_id:
    description: |
      Return results for this extract ID.
    type: integer
    required: false
  extract_id[]:
    description: |
      Return results for these extract IDs.
    type: integer array
    required: false
  extract_origin:
    description: |
      One of: 'Extract', 'Specimen', 'Lot', 'RangedLot', 'Otu', 'CollectionObject'
    type: string
    required: false
  extract_start_date_range:
    description: |
      A date in the format yyyy-mm-dd.
    type: datetime
    required: false
  otu_id:
    description: |
      Return results for this OTU ID.
    type: integer
    required: false
  otu_id[]:
    description: |
      Return results for these OTU IDs.
    type: integer array
    required: false
  protocol_id:
    description: |
      Return results for this protocol ID.
    type: integer
    required: false
  repository_id:
    description: |
      Return results for this repository ID.
    type: integer
    required: false
  repository_id[]:
    description: |
      Return results for these repository IDs.
    type: integer array
    required: false
  sequences:
    description: |
      Include results with sequences.
    type: boolean
    required: false
  taxon_name_id:
    description: |
      Return all extracts linked to OTUs AND CollectionObject that is self or descendant linked
    type: integer
    required: false
  taxon_name_id[]:
    description: |
      Return all extracts linked to OTUs AND CollectionObject that is self or descendant linked
    type: integer array
    required: false
  verbatim_anatomical_origin:
    description: |
      Return result for this anatomical origin.
    type: string
    required: false

responses:
  200:
    body:
      application/json:
        type: Extract[]
        maxItems: 100
        uniqueItems: true
        example: !include /examples/extracts-result-example.json

