is: [citations, tags, pageable: { default_per: 50, max_per: 1000 }]
queryParameters:
  biocuration_class_id:
    description: |
      Include metadata for biocuration classes by id
    type: string integer
    required: false
  biocuration_class_id[]:
    description: |
      Include metadata for biocuration classes by id array
    type: integer array
    required: false
  collection_object_id:
    description: |
      Identifier associated with collection object
    type: string integer
    required: false
  collection_object_id[]:
    description: |
      Identifier associated with collection object
    type: integer array
    required: false
  collection_object_scope:
    description: |
      Return Images associated with one or more of below:
    type: string
    enum: [all:, :collection_objects, :observations, :collecting_events]
    required: false
  depictions:
    description: |
      Return image(s) true: imahe is used in a depiction; false: not used; nil: not applied.
    type: boolean
    required: false
  depiction_object_type:
    description: |
      Restricts Images to those that depict one or more names of classes.
    type: string
    required: false
  image_id:
    description: |
      ID for the image
    type: string integer
    required: false
    example:  1
  image_id[]:
    description: |
      List of IDs for images e.g., image_id[]=34&image_id[]=398&image_id[]=726
    type: integer array
    required: false
  otu_id:
    description: |
      ID for a specific OTU
    type: string integer
    required: false
  otu_id[]:
    description: |
      List of OTU IDs e.g., otu_id[]=768&otu_id[]=1024&otu_id[]=2047
    type: integer array
    required: false
otu_scope:
    description: |
      One or more of:

        :all (default, includes all below)
        :otu (those on the OTU)
        :otu_observations (those on just the OTU)
        :collection_object_observations (those on just those determined as the OTU)
        :collection_objects (those on just those on the collection objects)
        :type_material (those on CollectionObjects that have TaxonName used in OTU)
        :type_material_observations (those on CollectionObjects that have TaxonName used in OTU)
        :coordinate_otus  If present adds both.  Use downstream substraction to do diffs of with/out?

    type: string array
    enum: [:all, :otu, :otu_observations, :collection_object_observations, :collection_objects, :type_material, :type_material_observations, :coordinate_otus]
    required: false
  otu_scope[]:
    description: |
      One or more of:

        :all (default, includes all below)
        :otu (those on the OTU)
        :otu_observations (those on just the OTU)
        :collection_object_observations (those on just those determined as the OTU)
        :collection_objects (those on just those on the collection objects)
        :type_material (those on CollectionObjects that have TaxonName used in OTU)
        :type_material_observations (those on CollectionObjects that have TaxonName used in OTU)
        :coordinate_otus  If present adds both.  Use downstream substraction to do diffs of with/out?
    type: string array
    enum: [:all, :otu, :otu_observations, :collection_object_observations, :collection_objects, :type_material, :type_material_observations, :coordinate_otus]
    required: false
  sled_image_id:
    description: |
      ID for a specific SLED image
    type: integer
    required: false
  sled_image_id[]:
    description: |
      List of IDs for specific SLED images
    type: integer array
    required: false
  source_id:
    description: |
      ID of a specific image source.
    type: integer
  source_id[]:
    description: |
      List of IDs for specific image sources.
    type: integer array
    required: false
  taxon_name_id:
    description: |
      ID for a specific taxon name
    type: string integer
    required: false
  taxon_name_id[]:
    description: |
      List of IDs for specific taxon names
    type: integer array
    required: false
  taxon_name_id_target:
    description: |
      ID for a specific taxon name
    type: string integer
    required: false

responses:
  200:
    body:
      application/json:
        type: Image[]
        maxItems: 100
        uniqueItems: true
        example: !include /examples/images-result-example.json
