is: [pageable: { default_per: 50, max_per: 1000 }]
queryParameters:
  author:
    description: |
      Filter by author (inside author property). Matching is case insensitive. Use " " for "and". See also `exact`.
    type: string
    required: false
    example: "Rehn Hebard"
  author_id:
    description: |
        Filter by this author ID.
      type: integer
      required: false
  author_id[]:
    description: |
        Filter by author IDs
    type: integer array
    required: false
  author_id_or:
    description: |
      ?? similar to collection_object
    type: boolean
    required: false
  bibtex_type:
  bibtex_type[]:
  citation_object_type[]:
    description: |
      Get source metadata associated with these types (Source::verbatim, Source::human, Source::Bibtex)
    type: string
    required: false
  citations:
    description: |
      Get source metadata associated with these citation IDs
    type: integer
    required: false
  citations_on_otus:
  descendants:
  documents:
    description: |
      get sources matching documents
    type: boolean
    required: false
  empty:
  empty[]:
  exact_author:
    description: |
      Metadata for only the exact author string provided (inside author property). Matching is case insensitive.
    type: string
    required: false
  exact_title:
    description: |
      Metadata selected for only exact title match
    type: boolean
    required: false
  identifier:
    description: |
      Identifier associated with source
    type: string
    required: false
  identifier_end:
    description: |
      Last part of identifier associated with source
    type: string
    required: false
  identifier_exact:
    description: |
      Exact identifier associated with source
    type: string
    required: false
  identifier_start:
    description: |
      First part of identifier associated with source
    type: string
    required: false
  ids[]:
     description: |
       Filter by source IDs
     type: integer array
     required: false
  in_project:
    description: |
      Search only this project for the source metadata
    type: boolean
    required: false
    example: true
  keyword_id_and:
    description: |
      List of keyword IDs for sources where all enumerated keywords are present.
    type: integer array
    required: false
  keyword_id_and[]:
    description: |
      List of keyword IDs for sources where all enumerated keywords are present.
    type: integer array
    required: false
  keyword_id_or:
    description: |
      List of keyword IDs for sources where all enumerated keywords are present.
    type: integer array
    required: false
  keyword_id_or[]:
    description: |
      List of keyword IDs for sources where any of the enumerated keywords are present.
    type: integer array
    required: false
  nomenclature:
    description: |
      include nomenclature metadata
    type: boolean
    required: false
  not_empty:
  notes:
    description: |
      include notes metadata
    type: boolean
    required: false
  project_id:
    description: |
      The project for the source search
    type: integer
    required: true
    example: 2
  query_term:
    description: |
      ??
    type: boolean
    required: false
  roles:
    description: |
      include metadata for roles
    type: boolean
    required: false
    example: false
  serial:
  serial_id:
  serial_id[]:
  source_id:
  source_id[]:
  source_type:
    description: |
      type of source, e.g., Source::BibTex, Source::verbatim, Source::human
    type: string
    required: false
  taxon_name_id:
  taxon_name_id[]:
  title:
    description: |
      title of the source, e.g., "Studies in American Tettigoniidae"
    type: string
    required: false
  topic_id:
    description: |
      Get source metadata associated with these topic IDs
    type: integer
    required: false
  topic_id[]:
    description: |
      Get source metadata associated with these topic IDs
    type: integer
    required: false
  user_date_end:
    description:
      Limit search to user dates prior
    type: string
    required: false
  user_date_start:
    description:
      Limit search to user dates later
    type: string
    required: false
  with_doi:
    description: |
      include metadata for sources having Digital Object Identifier
    type: boolean
    required: false
  with_title:
    description: |
      include metadata for sources having Digital Object Identifier
    type: boolean
    required: false
  year_end:
    description: |
      end year of the source date range
    type: integer
    required: false
  year_start:
    description: |
      start year of the source date range
    type: integer
    required: false

responses:
  200:
    body:
      application/json:
        type: Source[]
        maxItems: 100
        uniqueItems: true
        example: !include /examples/sources-result-example.json
