type: object
properties:
  id:
    description: TaxonName instance identifier
    type: number
    example: 25225
  name:
    description: |
      The fully latinized string (monomimial) of a code governed taxonomic biological name not 
      applicable for Combinations, they are derived from their pieces.
    type: string
    example: asymmetricus
  parent_id:
    description: |
      The id of the parent taxon. The parent child relationship is exclusively organizational. All statuses and relationships
      of a taxon name must be explicitly defined via taxon name relationships or classifications. The parent of a taxon name
      can be thought of as  "the place where you'd find this name in a hierarchy if you knew literally *nothing* else about that name."
      In practice read each monomial in the name (protonym or combination) from right to left, the parent is the parent of the last monomial read.
      There are 3 simple rules for determening the parent of a Protonym or Combination:
        1) the parent must always be at least one rank higher than the target names rank
        2) the parent of a synonym (any sense) is the parent of the synonym's valid name
        3) the parent of a combination is the parent of the highest ranked monomial in the epithet (almost always the parent of the genus)
    type: integer
    example: 2
  year_of_publication:
    description: |
      Sensu ICZN - the 4 digit year when this name was published, i.e. made available. Not the publishers date stamped on the title page,
      but the actual date of publication. Precedence for taxon name publication year is TaxonName#year_of_publication, Source#year, Source#stated_year.
    type: integer
    example: nil
  verbatim_author:
    description: |
      The verbatim author string as provided ? is not post-filled in when Source is referenced !?
    type: string
  rank_string:
    description: |
      Rank (Kindom, Phylum...) as a string, like {NomenclaturalRank::Iczn::SpeciesGroup::Species}
    type: string
  type:
    description: |
      The subclass of this taxon name, e.g. Protonym or Combination.
    type: string
  masculine_name:
    description: |
      Species name which are adjective or participle change depending on the gender of the genus.
      3 fields provide alternative species spelling. The part_of_speech is designated as a taxon_name_classification.
      The gender of a genus also designated as a taxon_name_classification.
    type: string
  feminine_name:
    description: |
      Species name which are adjective or participle change depending on the gender of the genus.
      3 fields provide alternative species spelling. The part_of_speech is designated as a taxon_name_classification.
      The gender of a genus also designated as a taxon_name_classification.
    type: string
  neuter_name:
    description: |
      Species name which are adjective or participle change depending on the gender of the genus.
      3 fields provide alternative species spelling. The part_of_speech is designated as a taxon_name_classification.
      The gender of a genus also designated as a taxon_name_classification.
    type: string
  project_id:
    description: |
      The project ID
    type: integer
  verbatim_name:
    description: |
      A representation of what the combination (fully spelled out) or protonym (monomial) *looked like* in its originating publication.
      The sole purpose of this string is to represent visual differences from what is recorded in the
      latinized version of the name (Protonym#name, Combination#cached) from what was originally transcribed.
      This string should NOT include the author year (see verbatim_author and year_of_publication for those data).
    type: string
  etymology:
    description: |
      The derivation and history of the name in written form.
    type: string
  cached:
    description: |
      Genus-species combination for genus and lower, monomial for higher. The string has NO html, and no author/year.
    type: string
  cached_html:
    description: |
      As in `cached` but with <i></i> tags.
    type: string
  cached_author_year:
    description: |
      Author and year string with parentheses where necessary, i.e. with context of present placement for ICZN.
    type: string | nil
  nomenclatural_code:
    description: |
      The name of the nomenclatural code, as a short symbol (:iczn, :icn), or nil
    type: string | nil
  name_string:
    description: |
      The current name/combination with author year, without HTML.
    type: string
  original_combination:
    description: |
      The name in original combination, with author year, with HTML.
    type: string
